// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  funstuff_slice: dynamic(() => import("./FunstuffSlice")),
  highlights_slice: dynamic(() => import("./HighlightsSlice")),
  nieuw_slice: dynamic(() => import("./NieuwSlice")),
};
